name: 'publish'

on:
  push:
    branches:
      - release
  workflow_dispatch: # Allows manual triggering from the GitHub UI

# This workflow will trigger on each push to the `release` branch OR when manually dispatched.

jobs:
  publish-tauri:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: 'macos-latest' # for Arm based macs (M1 and above).
            args: '--target aarch64-apple-darwin'
          - platform: 'macos-latest' # for Intel based macs.
            args: '--target x86_64-apple-darwin'
          - platform: 'ubuntu-22.04' # for Tauri v2.
            args: ''
          - platform: 'windows-latest'
            args: ''

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          # Those targets are only used on macos runners so it's in an `if` to slightly speed up windows and linux builds.
          targets: ${{ matrix.platform == 'macos-latest' && 'aarch64-apple-darwin,x86_64-apple-darwin' || '' }}

      - name: install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-22.04' # This must match the platform value defined above.
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf libmpv-dev
        # webkitgtk 4.1 is for Tauri v2.

      # === End Platform Dependencies ===

      - name: install frontend dependencies
        run: npm ci # Use npm ci for cleaner installs in CI

      # === Build Frontend CSS ===
      - name: Build Tailwind CSS
        run: npm run build:css # Runs the build:css script from the root package.json

      # === Install MSYS2 for gendef/dlltool (Windows Only) ===
      - name: Install MSYS2
        if: matrix.platform == 'windows-latest'
        run: choco install msys2 --params "/InstallDir:C:\msys64" -y

      # === Add MSYS2 tools to PATH (Windows Only) ===
      - name: Add MSYS2 tools to PATH
        if: matrix.platform == 'windows-latest'
        run: echo "C:\msys64\mingw64\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
        shell: pwsh # Use powershell for this step

      # === MPV/Linker Setup ===
      - name: Download and Setup Pre-compiled mpv (macOS)
        if: startsWith(matrix.platform, 'macos-')
        env:
          # Replace with the actual URL to the release assets
          RELEASE_URL: https://github.com/eko5624/mpv-mac/releases/download/2025-04-07 
          # !!! Verify these asset names on the release page !!!
          ARM64_ASSET: libmpv.arm64.dylib 
          X86_64_ASSET: libmpv.x86_64.dylib
        run: |
          echo "Downloading pre-compiled mpv libraries..."
          mkdir -p src-tauri/libs/macos # Create directory for the library
          
          TARGET_ARCH="${{ matrix.args }}" # Get the target string like --target aarch64-apple-darwin
          DOWNLOAD_URL=""
          TARGET_DYLIB=""
          MPV_LIB_PATH="libs/macos" # Relative path for linker/build script
          CONFIG_CONTENT=""
          
          echo "Build target args: $TARGET_ARCH"
          mkdir -p .cargo # Ensure .cargo directory exists
          
          if [[ "$TARGET_ARCH" == *"aarch64-apple-darwin"* ]]; then
            echo "Setting up for ARM64 build..."
            DOWNLOAD_URL="${RELEASE_URL}/${ARM64_ASSET}"
            TARGET_DYLIB="src-tauri/libs/macos/libmpv.2.dylib"
            CONFIG_CONTENT="[target.aarch64-apple-darwin]\nrustflags = [\"-L\", \"$MPV_LIB_PATH\"]"
          elif [[ "$TARGET_ARCH" == *"x86_64-apple-darwin"* ]]; then
            echo "Setting up for X86_64 build..."
            DOWNLOAD_URL="${RELEASE_URL}/${X86_64_ASSET}"
            TARGET_DYLIB="src-tauri/libs/macos/libmpv.2.dylib"
            CONFIG_CONTENT="[target.x86_64-apple-darwin]\nrustflags = [\"-L\", \"$MPV_LIB_PATH\"]"
          else
            echo "::error::Could not determine download URL for target $TARGET_ARCH"
            exit 1
          fi
          
          # Download the correct dylib
          echo "Downloading from $DOWNLOAD_URL to $TARGET_DYLIB"
          curl -L "$DOWNLOAD_URL" -o "$TARGET_DYLIB"
          if [ $? -ne 0 ]; then
            echo "::error::Failed to download $DOWNLOAD_URL"
            exit 1
          fi
          echo "Downloaded $(basename $DOWNLOAD_URL)"
          ls -l src-tauri/libs/macos # Verify download
          
          # Create the config file
          echo "Creating .cargo/config.toml"
          echo -e "$CONFIG_CONTENT" > .cargo/config.toml
          cat .cargo/config.toml # Print content for verification
          
          # Set LIBMPV_LIB_DIR for the build script (relative path)
          echo "Setting LIBMPV_LIB_DIR=$MPV_LIB_PATH"
          echo "LIBMPV_LIB_DIR=$MPV_LIB_PATH" >> $GITHUB_ENV

      - name: Download libmpv-2.dll (Windows)
        if: matrix.platform == 'windows-latest'
        run: |
          Invoke-WebRequest -Uri 'https://cautioned.co/libmpv-2.dll' -OutFile 'src-tauri/libmpv-2.dll'
          echo "libmpv-2.dll downloaded to src-tauri/"
      
      - name: Generate MPV .lib file (Windows)
        if: matrix.platform == 'windows-latest'
        # Run AFTER installing MSYS2 and adding to PATH
        shell: powershell # Ensure powershell is used
        run: |
          .\src-tauri\generate-lib.ps1
          echo "MPV .lib file generated (hopefully)"
      # === End MPV/Linker Setup ===

      # === Tauri Build and Release (Single Step) ===
      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # RUSTFLAGS and LIBMPV_LIB_DIR are now set via $GITHUB_ENV in previous steps
          TAURI_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
          TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}
          TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY_PASSWORD }}
          TAURI_KEY_PASSWORD: ${{ secrets.TAURI_KEY_PASSWORD }}
        with:
          tagName: app-v__VERSION__ # The action automatically replaces __VERSION__ with the app version.
          releaseName: 'App v__VERSION__'
          releaseBody: 'See the assets to download this version and install.'
          releaseDraft: true # Creates a draft release. Change to false to publish automatically.
          prerelease: false # Set to true if releasing pre-releases.
          includeUpdaterJson: true
          args: ${{ matrix.args }}
          # Note: Assumes `libmpv-2.dll` in `src-tauri/resources` (tauri.conf.json) is sufficient for bundling on Windows. 