name: 'publish'

on:
  workflow_dispatch:
  push:
    branches:
      - release

jobs:
  publish-tauri:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: 'macos-latest' # for Arm based macs (M1 and above).
            args: '--target aarch64-apple-darwin'
          - platform: 'macos-latest' # for Intel based macs.
            args: '--target x86_64-apple-darwin'
          - platform: 'ubuntu-22.04'
            args: ''
          - platform: 'windows-latest'
            args: ''

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies (Ubuntu only)
        if: matrix.platform == 'ubuntu-22.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf libmpv-dev

      - name: Install mpv (macOS only)
        if: matrix.platform == 'macos-latest'
        run: |
          brew install mpv
          find /opt/homebrew/lib -name "libmpv*.dylib" -ls || find /usr/local/lib -name "libmpv*.dylib" -ls || echo "libmpv.dylib not found"

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: 'npm'

      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.platform == 'macos-latest' && 'aarch64-apple-darwin,x86_64-apple-darwin' || '' }}

      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: './src-tauri -> target'

      - name: Install frontend dependencies
        run: yarn install

      - name: Download and copy libmpv-2.dll
        shell: bash
        run: |
          curl -L -o libmpv-2.dll http://cautioned.co/libmpv-2.dll
          mkdir -p src-tauri/lib/64
          mv libmpv-2.dll src-tauri/lib/64/
          echo "Copying libmpv-2.dll to all necessary locations..."
          cp src-tauri/lib/64/libmpv-2.dll src-tauri/libmpv-2.dll
          cp src-tauri/lib/64/libmpv-2.dll libmpv-2.dll
          mkdir -p src-tauri/target/debug
          mkdir -p src-tauri/target/release
          cp src-tauri/lib/64/libmpv-2.dll src-tauri/target/debug/libmpv-2.dll
          cp src-tauri/lib/64/libmpv-2.dll src-tauri/target/release/libmpv-2.dll

      - name: Build CSS for templates
        run: |
          cd src-tauri/templates
          if [ -f package.json ]; then
            npm install
          else
            echo "No package.json found in src-tauri/templates/, installing tailwindcss globally"
            npm install -g tailwindcss
          fi
          npm run build:css
          cd ../..

      - name: Build and publish with Tauri
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: app-v__VERSION__
          releaseName: 'App v__VERSION__'
          releaseBody: 'See the assets to download this version and install.'
          releaseDraft: true
          prerelease: false
          args: ${{ matrix.args }}
